const test = require("node:test");
const assert = require("node:assert/strict");
const Task = require("../src/models/Task");
const Order = require("../src/models/Order");
const User = require("../src/models/User");
const { confirmCodCollection } = require("../src/controllers/taskController");
const res = () => ({ statusCode: 200, status(code) { this.statusCode = code; return this; }, json(value) { this.body = value; return this; } });
test("collection endpoint checks GPS and explicit consent, records the server total once", async (t) => {
  const tech = "507f1f77bcf86cd799439011";
  const order = { _id: "507f1f77bcf86cd799439012", orderCode: "COD-TEST", paymentMethod: "cod", workflowStatus: "to_install", dispatchedAt: new Date(), assignedTechnicianId: tech, totalAmount: 12345, receipt: {} };
  const task = { _id: "507f1f77bcf86cd799439013", status: "in-progress", assignedTechnicianId: tech, payload: { orderId: String(order._id) }, toJSON() { return { id: String(this._id), status: this.status }; } };
  t.mock.method(Task, "findOne", async () => task);
  t.mock.method(Order, "findOne", async () => order);
  t.mock.method(User, "find", () => ({ select: async () => [] }));
  let writes = 0;
  t.mock.method(Order, "updateOne", async (filter, update) => {
    assert.equal(filter.assignedTechnicianId, tech);
    assert.equal(filter["codCollection.collectedAt"], null);
    if (order.codCollection?.collectedAt) return { modifiedCount: 0 };
    writes++;
    order.codCollection = update.$set.codCollection;
    order.paymentStatus = update.$set.paymentStatus;
    order.receipt.amountPaid = update.$set["receipt.amountPaid"];
    return { modifiedCount: 1 };
  });
  const req = { authUser: { role: "technician", _id: tech }, params: { taskId: String(task._id) }, body: { confirmed: true, amount: 1 } };
  const noGps = res(); await confirmCodCollection(req, noGps);
  assert.equal(noGps.statusCode, 409);
  task.payload.checkIn = { checkedInAt: new Date().toISOString(), latitude: 14.5, longitude: 121 };
  const noConsent = res(); await confirmCodCollection({ ...req, body: {} }, noConsent);
  assert.equal(noConsent.statusCode, 400);
  const admin = res(); await confirmCodCollection({ ...req, authUser: { ...req.authUser, role: "admin" } }, admin);
  assert.equal(admin.statusCode, 403);
  const ok = res(); await confirmCodCollection(req, ok);
  assert.equal(ok.statusCode, 200);
  assert.equal(order.receipt.amountPaid, 12345);
  assert.equal(order.paymentStatus, "paid");
  assert.equal(order.codCollection.technicianId, tech);
  const timestamp = order.codCollection.collectedAt;
  const retry = res(); await confirmCodCollection(req, retry);
  assert.equal(retry.statusCode, 200);
  assert.equal(writes, 1);
  assert.equal(order.codCollection.collectedAt, timestamp);
});
